/**
 * Builds the real-proof fixture for test/PrivateCredit.t.sol.
 *
 * Reproduces, in JavaScript, exactly the registry state the Foundry test constructs — two scored
 * addresses, one with a commitment — computes the Poseidon tree the same way the contract does,
 * then has nargo + bb prove "score ≥ 500" for the committed address. The test asserts the contract's
 * root equals the JS root before it ever touches the verifier, so a Poseidon or tree-shape
 * mismatch between Solidity and the circuit fails loudly rather than as an opaque InvalidProof.
 *
 * Run: npm run zk:fixture   (needs nargo and bb on PATH or in ~/.nargo/bin and ~/.bb)
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { poseidon1, poseidon2 } from 'poseidon-lite'

const DEPTH = 16
const CIRCUIT = fileURLToPath(new URL('../circuits/credit_threshold/', import.meta.url))
const OUT = fileURLToPath(new URL('../test/fixtures/zk-threshold.json', import.meta.url))
const NARGO = process.env.NARGO ?? `${homedir()}/.nargo/bin/nargo`
const BB = process.env.BB ?? `${homedir()}/.bb/bb`

// Mirrors the Foundry test: address(0xA11CE) with 8 counted repayments (score 500), address(0xB0B)
// with one (325). Alice sets a commitment; Bob does not.
const ALICE = 0xa11cen
const BOB = 0xb0bn
const ALICE_SCORE = 500n
const BOB_SCORE = 325n
const THRESHOLD = 500
const SECRET = 0x1f2e3d4c5b6a79880000000000000000000000000000000000000000c0ffee01n
const NULLIFIER_DOMAIN = 1n

const hex = (v: bigint) => `0x${v.toString(16).padStart(64, '0')}`
const addr = (v: bigint) => `0x${v.toString(16).padStart(40, '0')}`
const leaf = (address: bigint, score: bigint, commitment: bigint) => poseidon2([poseidon2([address, score]), commitment])

function main() {
    const commitment = poseidon1([SECRET])
    const nullifier = poseidon2([SECRET, NULLIFIER_DOMAIN])

    const zeros: bigint[] = [0n]
    for (let i = 1; i <= DEPTH; i++) zeros.push(poseidon2([zeros[i - 1], zeros[i - 1]]))

    // Leaf 0 is Alice (first address the registry ever touched), leaf 1 is Bob.
    const leaves = [leaf(ALICE, ALICE_SCORE, commitment), leaf(BOB, BOB_SCORE, 0n)]
    const siblings: bigint[] = [leaves[1]]
    for (let i = 1; i < DEPTH; i++) siblings.push(zeros[i])

    let node = leaves[0]
    for (let i = 0; i < DEPTH; i++) node = poseidon2([node, siblings[i]]) // index 0: always the left child
    const root = node

    const prover = [
        `root = "${hex(root)}"`,
        `threshold = ${THRESHOLD}`,
        `nullifier_defaults = 0`,
        `nullifier = "${hex(nullifier)}"`,
        `secret = "${hex(SECRET)}"`,
        `address = "${hex(ALICE)}"`,
        `score = ${ALICE_SCORE}`,
        `index = 0`,
        `siblings = [${siblings.map((s) => `"${hex(s)}"`).join(', ')}]`,
        '',
    ].join('\n')
    writeFileSync(`${CIRCUIT}Prover.toml`, prover)

    if (!existsSync(`${CIRCUIT}target/credit_threshold.json`) || !existsSync(`${CIRCUIT}target/vk`)) {
        throw new Error('Circuit not built. Run `npm run zk:build` first.')
    }

    console.log('Executing the circuit…')
    execFileSync(NARGO, ['execute', 'zkfixture'], { cwd: CIRCUIT, stdio: 'inherit' })

    console.log('Proving (UltraHonk, keccak oracle, zero-knowledge)…')
    execFileSync(
        BB,
        ['prove', '-b', 'target/credit_threshold.json', '-w', 'target/zkfixture.gz', '-o', 'target/zkfixture', '--oracle_hash', 'keccak', '--zk', '--output_format', 'bytes_and_fields'],
        { cwd: CIRCUIT, stdio: 'inherit' }
    )
    console.log('Verifying natively…')
    execFileSync(BB, ['verify', '-k', 'target/vk', '-p', 'target/zkfixture/proof', '-i', 'target/zkfixture/public_inputs', '--oracle_hash', 'keccak', '--zk'], {
        cwd: CIRCUIT,
        stdio: 'inherit',
    })

    const proof = `0x${readFileSync(`${CIRCUIT}target/zkfixture/proof`).toString('hex')}`
    const publicInputs = JSON.parse(readFileSync(`${CIRCUIT}target/zkfixture/public_inputs_fields.json`, 'utf8')) as string[]

    writeFileSync(
        OUT,
        JSON.stringify(
            {
                note: 'Generated by script/make-zk-fixture.ts. Mirrors the scenario in test/PrivateCredit.t.sol.',
                alice: addr(ALICE),
                bob: addr(BOB),
                aliceScore: Number(ALICE_SCORE),
                bobScore: Number(BOB_SCORE),
                secret: hex(SECRET),
                commitment: hex(commitment),
                nullifier: hex(nullifier),
                root: hex(root),
                threshold: THRESHOLD,
                defaults: 0,
                publicInputs,
                proof,
            },
            null,
            2
        ) + '\n'
    )
    console.log(`\nWrote ${OUT}`)
    console.log(`  root       ${hex(root)}`)
    console.log(`  nullifier  ${hex(nullifier)}`)
    console.log(`  proof      ${(proof.length - 2) / 2} bytes`)
}

main()
