'use client'

import Link from 'next/link'
import { useState } from 'react'
import { BrowserProvider, isHexString } from 'ethers'
import { ArrowUpRight, Check, Loader2, Search } from 'lucide-react'

import { Notice, Row, useApp } from '@/components/app-shell'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { ACTION_LABELS, PROTOCOL_POOLS, SCORE, explorerUrl, fetchProof, shorten, sourceExplorerUrl, submitProof, type ProofOutcome, type ProofPayload } from '@/lib/creditpass'
import { ensureCreditcoinNetwork } from '@/lib/wallet'

type Step = 'idle' | 'checking' | 'ready' | 'submitting' | 'done'

/**
 * Prove one Ethereum transaction from the browser.
 *
 * Paste a hash; the API works out which pool and event it is and fetches the Attestcoin proof; the
 * wallet submits it to the ASC; the registry's own events say whether it counted. Every step that
 * could surprise the user — wrong borrower, already proved, inside the spam window — is said
 * before the signature is asked for, not after the revert.
 */
export function ProveHistory({ compact = false }: { compact?: boolean }) {
    const { wallet, provider, snapshot, refresh } = useApp()
    const [hash, setHash] = useState('')
    const [step, setStep] = useState<Step>('idle')
    const [proof, setProof] = useState<ProofPayload | null>(null)
    const [outcome, setOutcome] = useState<ProofOutcome | null>(null)
    const [error, setError] = useState<string | null>(null)

    const valid = isHexString(hash.trim(), 32)
    const demo = Boolean(snapshot?.demo)

    const check = async () => {
        setError(null)
        setOutcome(null)
        setStep('checking')
        try {
            setProof(await fetchProof(hash.trim()))
            setStep('ready')
        } catch (e) {
            setError(e instanceof Error ? e.message : String(e))
            setStep('idle')
        }
    }

    const submit = async () => {
        if (!proof || !provider) return
        setError(null)
        setStep('submitting')
        try {
            await ensureCreditcoinNetwork(provider)
            const signer = await new BrowserProvider(provider).getSigner()
            setOutcome(await submitProof(signer, proof))
            setStep('done')
            refresh()
        } catch (e) {
            setError(e instanceof Error ? e.message : String(e))
            setStep('ready')
        }
    }

    const reset = () => {
        setHash('')
        setProof(null)
        setOutcome(null)
        setError(null)
        setStep('idle')
    }

    // Everything the contract would object to, said up front.
    const notMine = proof && wallet && proof.borrower.toLowerCase() !== wallet.toLowerCase()
    const alreadyProved = proof && snapshot?.history.some((h) => h.protocolId === proof.protocolId && h.sourceBlock === proof.sourceBlock && h.action === proof.action)
    const last = snapshot?.profile.lastCountedBlock ?? 0
    const insideGap = proof && proof.action === 0 && !notMine && last > 0 && proof.sourceBlock <= last + SCORE.minBlockGap
    const points = proof ? (proof.action === 0 ? `+${SCORE.perRepayment}` : proof.action === 1 ? `−${SCORE.liquidation}` : '0') : ''

    return (
        <Card className="p-5">
            <div className="flex items-center justify-between">
                <div className="text-lg font-semibold tracking-tight">Prove a transaction</div>
                <div className="text-muted-foreground text-xs">Ethereum mainnet → Creditcoin</div>
            </div>
            {!compact && (
                <p className="text-muted-foreground mt-2 text-sm">
                    Paste the hash of a repayment, borrow or liquidation you made on Aave V3, Spark or Morpho Blue. The proof is generated by the
                    Attestcoin service and verified on chain; nobody reports anything on your behalf.
                </p>
            )}

            {step === 'done' && outcome ? (
                <div className="mt-4">
                    <div className="flex items-center gap-2 text-sm font-medium">
                        <span className="bg-foreground text-background inline-flex size-5 items-center justify-center rounded-full">
                            <Check className="size-3" />
                        </span>
                        Proof verified on Creditcoin
                    </div>
                    <div className="bg-muted/40 mt-3 space-y-2 rounded-xl px-3 py-2.5 text-xs">
                        <Row label="Credited to" value={shorten(outcome.user)} />
                        <Row
                            label="Score effect"
                            value={outcome.counted === null ? 'Recorded (no score change for this event type)' : outcome.counted ? `Counted · score now ${outcome.scoreAfter}` : 'Recorded but not counted'}
                            strong
                        />
                        {outcome.skipReason && <p className="text-muted-foreground pt-1">Registry said: {outcome.skipReason}.</p>}
                    </div>
                    <div className="mt-3 flex items-center justify-between text-xs">
                        <Link
                            href={explorerUrl('tx', outcome.txHash)}
                            target="_blank"
                            rel="noreferrer"
                            className="text-muted-foreground hover:text-foreground inline-flex items-center gap-1">
                            View on Blockscout <ArrowUpRight className="size-3" />
                        </Link>
                        <button
                            type="button"
                            onClick={reset}
                            className="text-muted-foreground hover:text-foreground">
                            Prove another
                        </button>
                    </div>
                </div>
            ) : (
                <>
                    <div className="relative mt-4">
                        <Search className="text-muted-foreground pointer-events-none absolute left-3 top-1/2 size-3.5 -translate-y-1/2" />
                        <Input
                            value={hash}
                            spellCheck={false}
                            disabled={step === 'checking' || step === 'submitting'}
                            onChange={(e) => {
                                setHash(e.target.value)
                                setProof(null)
                                setStep('idle')
                            }}
                            onKeyDown={(e) => e.key === 'Enter' && valid && step === 'idle' && check()}
                            placeholder="Ethereum transaction hash 0x…"
                            className="h-11 pl-9 font-mono text-sm"
                        />
                    </div>

                    {proof && step !== 'idle' && (
                        <div className="bg-muted/40 mt-3 space-y-2 rounded-xl px-3 py-2.5 text-xs">
                            <Row label="Detected" value={`${proof.protocolName} · ${ACTION_LABELS[proof.action]}`} strong />
                            <Row label="Borrower" value={notMine ? `${shorten(proof.borrower)} (not your wallet)` : 'Your wallet'} />
                            <Row label="Source block" value={`#${proof.sourceBlock.toLocaleString()}`} />
                            <Row label="Proof" value={`${proof.siblings.length} Merkle siblings · ${proof.continuityRoots.length} continuity roots`} />
                            <Row label="Score effect if counted" value={`${points} points`} />
                        </div>
                    )}

                    {step === 'ready' && alreadyProved && <div className="mt-3"><Notice tone="warn">This transaction is already on this passport. The ASC will reject a second submission.</Notice></div>}
                    {step === 'ready' && notMine && !alreadyProved && (
                        <div className="mt-3">
                            <Notice tone="warn">You can still submit it, but it credits {shorten(proof!.borrower)}, not your wallet.</Notice>
                        </div>
                    )}
                    {step === 'ready' && insideGap && !alreadyProved && (
                        <div className="mt-3">
                            <Notice>
                                Within {SCORE.minBlockGap.toLocaleString()} blocks of your last counted repayment (#{last.toLocaleString()}). It will be recorded but the
                                registry will not count it toward the score.
                            </Notice>
                        </div>
                    )}

                    {step === 'ready' ? (
                        <Button
                            size="lg"
                            className="mt-4 h-12 w-full text-base"
                            disabled={!wallet || demo || Boolean(alreadyProved)}
                            onClick={submit}>
                            {!wallet ? 'Connect wallet to submit' : 'Submit proof'}
                        </Button>
                    ) : (
                        <Button
                            size="lg"
                            className="mt-4 h-12 w-full text-base"
                            disabled={!valid || step !== 'idle'}
                            onClick={check}>
                            {step === 'checking' || step === 'submitting' ? <Loader2 className="animate-spin" /> : null}
                            {step === 'checking' ? 'Building proof…' : step === 'submitting' ? 'Waiting for the wallet…' : 'Check transaction'}
                        </Button>
                    )}

                    <p className="text-muted-foreground mt-3 min-h-4 text-xs">
                        {error ??
                            (demo
                                ? 'Demo — proving is disabled until the contracts are deployed.'
                                : step === 'checking'
                                  ? 'Reading the receipt and asking the Attestcoin service for a proof. Deep history can take up to a minute.'
                                  : step === 'ready'
                                    ? 'Your wallet pays Creditcoin testnet gas. Nothing leaves your wallet but the signature.'
                                    : 'Find the hash on Etherscan under your address, filtered to the pool contract.')}
                    </p>

                    {!compact && step === 'idle' && (
                        <div className="text-muted-foreground mt-4 flex flex-wrap gap-x-4 gap-y-1 border-t pt-4 text-xs">
                            <span>Your history on</span>
                            {Object.entries(PROTOCOL_POOLS).map(([id, pool]) => (
                                <Link
                                    key={id}
                                    href={wallet ? `https://etherscan.io/advanced-filter?fadd=${wallet}&tadd=${pool}` : sourceExplorerUrl(3, 'address', pool)}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="hover:text-foreground inline-flex items-center gap-1">
                                    {['Aave V3', 'Spark', 'Morpho Blue'][Number(id)]} <ArrowUpRight className="size-3" />
                                </Link>
                            ))}
                        </div>
                    )}
                </>
            )}
        </Card>
    )
}
